### PR TITLE
Upgrade to Puppet Master 3.8.3

### PR DESCRIPTION
**Pull request by lorello**

### CODE REVIEW

**Comment by rfkrocktk** [comment]
Thanks for the commit, have you verified that it works? I don't have time at the moment to verify.

**Comment by lorello** [comment]
Yes i'm playing with it
Docker doesn't build with the old version for dependencies errors
L
Il 20/ott/2015 06:02 AM, "rfkrocktk" <notifications@github.com> ha scritto:

**Comment by rfkrocktk** [comment]
Verified that this works, merging.

**Comment by rfkrocktk** [comment]
Triggering a build on Docker Hub, enjoy!

**Pull request merged**
